#!/usr/bin/env bash
# Display username, user ID, and home directory from /etc/passwd using while loop

while IFS=':' read -r username _ userid _ _ _ home _; do
  echo "$username:$userid:$home"
done < /etc/passwd
